print("Feature message added")
print("Hello from FEATURE A")
print("Hello from FEATURE B")
print("Message from GitHub FEATURE A")
print("Message from GitHub FEATURE B")
print("Master change that conflicts")
